import type { Lecture, ThemeTokens, MindMap, TranscriptImage } from '@/types'
import { THEMES } from '@/types'

// v60: AI summary type for export
type AISummaryExport = {
  summary?: string
  inferredTitle?: string
  topics?: string[]
  keyPoints?: string[]
  formulas?: string[]
  questions?: string[]
}

// --------- Markdown export (v60: with mind map as bullets + images as ![]() ) ---------
export function lectureToMarkdown(
  l: Lecture,
  ai?: AISummaryExport,
): string {
  const lines: string[] = []
  const date = new Date(l.started_at).toLocaleString()
  const title = ai?.inferredTitle || l.title || 'Untitled'

  lines.push(`# ${title}`, '')
  if (l.subject)  lines.push(`**Subject:** ${l.subject}  `)
  if (l.lecturer) lines.push(`**Lecturer:** ${l.lecturer}  `)
  if (l.location) lines.push(`**Location:** ${l.location}  `)
  lines.push(`**Date:** ${date}  `)
  lines.push(`**Duration:** ${Math.round((l.duration_seconds || 0) / 60)} min  `)
  lines.push('')

  if (l.keywords?.length) {
    lines.push('## Keywords', '')
    lines.push(l.keywords.map((k) => `\`${k}\``).join(' · '), '')
  }

  // AI sections
  if (ai?.summary) {
    lines.push('## ✨ Summary', '', ai.summary, '')
  }
  if (ai?.topics?.length) {
    lines.push('## 📌 Topics covered', '')
    ai.topics.forEach((t, i) => lines.push(`${i + 1}. ${t}`))
    lines.push('')
  }
  if (ai?.keyPoints?.length) {
    lines.push('## 🔑 Key points', '')
    ai.keyPoints.forEach((k) => lines.push(`- ${k}`))
    lines.push('')
  }
  if (ai?.formulas?.length) {
    lines.push('## 📐 Formulas', '')
    ai.formulas.forEach((f) => lines.push(`- ${f}`))
    lines.push('')
  }
  if (ai?.questions?.length) {
    lines.push('## ❓ Questions', '')
    ai.questions.forEach((q) => lines.push(`- ${q}`))
    lines.push('')
  }

  // v60: Mind map as nested bullets
  if (l.mindmap_json) {
    lines.push('## 🧠 Mind map', '')
    lines.push(`- **${l.mindmap_json.center}**`)
    for (const branch of l.mindmap_json.branches || []) {
      lines.push(`  - ${branch.title}`)
      if (branch.subtitle) lines.push(`    - _${branch.subtitle}_`)
    }
    lines.push('')
  }

  // v60: Clean transcript with timestamps per segment
  lines.push('## 📝 Clean transcript', '')
  if (l.clean_transcript_edited && l.clean_transcript_edited.trim()) {
    lines.push(l.clean_transcript_edited, '')
  } else if (l.clean_segments && l.clean_segments.length > 0) {
    const fmtTime = (sec: number) => {
      const m = Math.floor(sec / 60)
      const s = Math.floor(sec % 60)
      return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
    }
    for (const seg of l.clean_segments) {
      lines.push(`**${fmtTime(seg.start)}–${fmtTime(seg.end)}**`, '', seg.text, '')
    }
  } else {
    lines.push(l.transcript_md || '_No transcript_', '')
  }

  // v60: Images
  if (l.transcript_images && l.transcript_images.length > 0) {
    lines.push('## 🖼️ Images', '')
    l.transcript_images.forEach((img, i) => {
      const caption = img.caption || `Image ${i + 1}`
      lines.push(`![${caption}](${img.url})`)
      if (img.caption) lines.push(`*${img.caption}*`)
      lines.push('')
    })
  }

  lines.push('---', '', '_Generated by Cotton Candy 🍭 · cottoncandy-s.com_')
  return lines.join('\n')
}

export function downloadText(filename: string, content: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// --------- PDF export (jsPDF) — v61: segments with timestamps ---------
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '')
  const r = parseInt(h.slice(0, 2), 16)
  const g = parseInt(h.slice(2, 4), 16)
  const b = parseInt(h.slice(4, 6), 16)
  return [r, g, b]
}

// Fetch image as base64 for PDF embedding
async function imageUrlToBase64(url: string): Promise<{ data: string; format: 'JPEG' | 'PNG' } | null> {
  try {
    const res = await fetch(url)
    if (!res.ok) return null
    const blob = await res.blob()
    const isJpeg = blob.type.includes('jpeg') || blob.type.includes('jpg')
    return new Promise((resolve) => {
      const reader = new FileReader()
      reader.onloadend = () => {
        const str = reader.result as string
        resolve({ data: str, format: isJpeg ? 'JPEG' : 'PNG' })
      }
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

// Strip emojis from text (jsPDF helvetica doesn't render them — they appear as garbage)
function stripEmojis(text: string): string {
  return text
    .replace(/[\u{1F000}-\u{1FFFF}]/gu, '')
    .replace(/[\u{2600}-\u{27BF}]/gu, '')
    .replace(/[\u{2300}-\u{23FF}]/gu, '')
    .replace(/[\u{1F300}-\u{1F9FF}]/gu, '')
    .replace(/[\u{2B00}-\u{2BFF}]/gu, '')
    .replace(/[\u{FE00}-\u{FE0F}]/gu, '')
    .replace(/[\u{200D}]/gu, '')
    .replace(/\s+/g, ' ')
    .trim()
}

// Format seconds to MM:SS
function fmtTime(sec: number): string {
  const m = Math.floor(sec / 60)
  const s = Math.floor(sec % 60)
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

// --------- HTML-based PDF for non-Latin languages (ZH, TA) ---------
// Uses browser print dialog with Google Fonts Noto for correct glyph rendering.
// Caller passes summaryLang — function picks the right font URL.
async function lectureToPdfHtml(
  l: Lecture,
  opts: { watermark?: boolean; theme?: ThemeTokens; ai?: AISummaryExport; summaryLang?: string } = {}
): Promise<void> {
  const ai = opts.ai
  const theme = opts.theme || THEMES.pink
  const title = ai?.inferredTitle || l.title || 'Lecture'
  const lang = opts.summaryLang || 'en'

  // Pick correct Noto font for the language
  const fontUrl =
    lang === 'zh'
      ? 'https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@400;700&display=swap'
      : lang === 'ta'
      ? 'https://fonts.googleapis.com/css2?family=Noto+Sans+Tamil:wght@400;700&display=swap'
      : lang === 'bm'
      ? 'https://fonts.googleapis.com/css2?family=Noto+Sans:wght@400;700&display=swap'
      : 'https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap'

  const fontFamily =
    lang === 'zh'
      ? "'Noto Sans SC', sans-serif"
      : lang === 'ta'
      ? "'Noto Sans Tamil', sans-serif"
      : lang === 'bm'
      ? "'Noto Sans', sans-serif"
      : "'Inter', sans-serif"

  const primaryColor = theme.primary || '#FF6B9D'
  const darkColor = theme.dark || '#1a1a1a'
  const grayColor = theme.gray || '#888888'

  // Build transcript HTML
  let transcriptHtml = ''
  if (l.clean_transcript_edited && l.clean_transcript_edited.trim()) {
    transcriptHtml = l.clean_transcript_edited
      .split(/\n+/)
      .filter(Boolean)
      .map(p => `<p>${p}</p>`)
      .join('')
  } else if (l.clean_segments && l.clean_segments.length > 0) {
    transcriptHtml = l.clean_segments.map(seg => `
      <div class="segment">
        <div class="ts">${fmtTime(seg.start)} – ${fmtTime(seg.end)}</div>
        <p>${seg.text}</p>
      </div>
    `).join('')
  } else {
    transcriptHtml = `<p>${l.transcript_md || 'No transcript'}</p>`
  }

  // Build AI sections HTML
  const section = (heading: string, items: string[], ordered = false) => {
    if (!items.length) return ''
    const tag = ordered ? 'ol' : 'ul'
    return `
      <div class="section">
        <h2>${heading}</h2>
        <${tag}>${items.map(i => `<li>${i}</li>`).join('')}</${tag}>
      </div>`
  }

  const aiHtml = [
    ai?.summary ? `<div class="section"><h2>${lang === 'zh' ? '摘要' : lang === 'ta' ? 'சுருக்கம்' : lang === 'bm' ? 'Ringkasan' : 'Summary'}</h2><p>${ai.summary}</p></div>` : '',
    ai?.topics?.length ? section(lang === 'zh' ? '涵盖主题' : lang === 'ta' ? 'தலைப்புகள்' : lang === 'bm' ? 'Topik' : 'Topics covered', ai.topics, true) : '',
    ai?.keyPoints?.length ? section(lang === 'zh' ? '关键点' : lang === 'ta' ? 'முக்கிய புள்ளிகள்' : lang === 'bm' ? 'Poin Utama' : 'Key points', ai.keyPoints) : '',
    ai?.formulas?.length ? section(lang === 'zh' ? '公式' : lang === 'ta' ? 'சூத்திரங்கள்' : lang === 'bm' ? 'Formula' : 'Formulas', ai.formulas) : '',
    ai?.questions?.length ? section(lang === 'zh' ? '问题' : lang === 'ta' ? 'கேள்விகள்' : lang === 'bm' ? 'Soalan' : 'Questions', ai.questions) : '',
  ].join('')

  // Mind map as nested list (HTML print — no canvas needed)
  let mindmapHtml = ''
  if (l.mindmap_json) {
    const heading = lang === 'zh' ? '思维导图' : lang === 'ta' ? 'மனவரைபடம்' : lang === 'bm' ? 'Peta Minda' : 'Mind map'
    const branches = (l.mindmap_json.branches || []).map(b =>
      `<li><strong>${b.title}</strong>${b.subtitle ? `<br><span class="sub">${b.subtitle}</span>` : ''}</li>`
    ).join('')
    mindmapHtml = `
      <div class="section">
        <h2>${heading}</h2>
        <p class="center-node">${l.mindmap_json.center || title}</p>
        <ul>${branches}</ul>
      </div>`
  }

  const transcriptHeading =
    lang === 'zh' ? '文字记录' : lang === 'ta' ? 'படியெடுக்கப்பட்டது' : lang === 'bm' ? 'Transkrip' : 'Clean transcript'

  const metaParts: string[] = []
  if (l.subject)  metaParts.push(l.subject)
  if (l.lecturer) metaParts.push(l.lecturer)
  if (l.location) metaParts.push(l.location)
  metaParts.push(new Date(l.started_at).toLocaleDateString())

  const watermarkLine = opts.watermark
    ? `<div class="watermark">Cotton Candy · upgrade to remove this line</div>`
    : `<div class="watermark">Generated by Cotton Candy 🍭 · cottoncandy-s.com</div>`

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link href="${fontUrl}" rel="stylesheet">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: ${fontFamily};
      font-size: 12pt;
      color: ${darkColor};
      line-height: 1.6;
      padding: 0;
    }

    /* Header band — matches jsPDF version */
    .header {
      background: ${primaryColor};
      padding: 24px 48px 20px;
      margin-bottom: 24px;
    }
    .header h1 {
      font-size: 20pt;
      font-weight: 700;
      margin-bottom: 6px;
    }
    .header .meta {
      font-size: 10pt;
      color: ${darkColor};
      opacity: 0.75;
    }

    .content { padding: 0 48px 48px; }

    .section { margin-bottom: 24px; }
    h2 {
      font-size: 13pt;
      font-weight: 700;
      color: ${primaryColor};
      margin-bottom: 10px;
      border-bottom: 1px solid #eee;
      padding-bottom: 4px;
    }
    p { margin-bottom: 8px; }
    ul, ol { padding-left: 20px; }
    li { margin-bottom: 4px; }
    .sub { font-size: 10pt; color: ${grayColor}; }

    /* Mind map center node pill */
    .center-node {
      display: inline-block;
      background: #1d1d1f;
      color: #fff;
      font-weight: 700;
      padding: 6px 18px;
      border-radius: 999px;
      margin-bottom: 10px;
      font-size: 11pt;
    }

    /* Transcript segments */
    .segment { margin-bottom: 14px; }
    .ts {
      font-size: 8.5pt;
      color: ${grayColor};
      font-weight: 700;
      margin-bottom: 2px;
    }
    .segment p { margin: 0; }

    /* Footer watermark */
    .watermark {
      margin-top: 32px;
      font-size: 9pt;
      color: ${grayColor};
      text-align: center;
      border-top: 1px solid #eee;
      padding-top: 10px;
    }

    @media print {
      @page { size: A4; margin: 0; }
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      /* Prevent segments from breaking mid-way */
      .segment { page-break-inside: avoid; }
      .section { page-break-inside: avoid; }
      /* Header colour must print */
      .header { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <div class="meta">${metaParts.join('  ·  ')}</div>
  </div>
  <div class="content">
    ${aiHtml}
    ${mindmapHtml}
    <div class="section">
      <h2>${transcriptHeading}</h2>
      ${transcriptHtml}
    </div>
    ${watermarkLine}
  </div>
</body>
</html>`

  const win = window.open('', '_blank')
  if (!win) {
    // Popup blocked — fallback: download as HTML and let user print manually
    downloadText(`${title}.html`, html, 'text/html')
    return
  }
  win.document.write(html)
  win.document.close()

  // Wait for Google Fonts to load before triggering print
  // fonts.googleapis.com can take 300–1200ms on first load
  const waitForFonts = () =>
    new Promise<void>((resolve) => {
      if (win.document.fonts && typeof win.document.fonts.ready === 'object') {
        win.document.fonts.ready.then(() => resolve())
      } else {
        setTimeout(resolve, 1200) // fallback for older browsers
      }
    })

  await waitForFonts()
  win.print()
  // Note: don't call win.close() — user needs the window open to complete Save As PDF
}

// --------- Main PDF export entry point ---------
// Routes to lectureToPdfHtml for non-Latin languages (zh, ta),
// jsPDF for Latin-based languages (en, bm).
export async function lectureToPdf(
  l: Lecture,
  opts: { watermark?: boolean; theme?: ThemeTokens; ai?: AISummaryExport; summaryLang?: string } = {}
) {
  const lang = opts.summaryLang || 'en'

  // Non-Latin: use HTML + browser print (Google Fonts Noto)
  if (lang === 'zh' || lang === 'ta') {
    return lectureToPdfHtml(l, opts)
  }

  // Latin (en, bm): original jsPDF path
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 48
  let y = M

  const theme = opts.theme || THEMES.pink
  const pink = hexToRgb(theme.primary)
  const dark = hexToRgb(theme.dark)
  const gray = hexToRgb(theme.gray)
  const soft = hexToRgb(theme.soft)
  const accent = hexToRgb(theme.primaryDark)

  const nextPage = () => { doc.addPage(); y = M }
  const ensure = (h: number) => { if (y + h > H - M) nextPage() }
  const wrap = (txt: string, maxWidth: number, fontSize: number) => {
    doc.setFontSize(fontSize)
    return doc.splitTextToSize(txt, maxWidth) as string[]
  }

  const ai = opts.ai
  const title = ai?.inferredTitle || l.title || 'Lecture'

  // HEADER BAND
  doc.setFillColor(...pink)
  doc.rect(0, 0, W, 90, 'F')
  doc.setTextColor(...dark)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text(stripEmojis(title), M, 52)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  const meta: string[] = []
  if (l.subject)  meta.push(stripEmojis(l.subject))
  if (l.lecturer) meta.push(stripEmojis(l.lecturer))
  if (l.location) meta.push(stripEmojis(l.location))
  meta.push(new Date(l.started_at).toLocaleDateString())
  doc.text(meta.join('  ·  '), M, 74)
  y = 120

  const heading = (text: string, color: [number, number, number] = accent) => {
    ensure(34)
    doc.setTextColor(...color)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text(stripEmojis(text), M, y); y += 22
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(...dark)
  }

  // SUMMARY
  if (ai?.summary) {
    heading('Summary')
    const ls = wrap(stripEmojis(ai.summary), W - 2 * M, 11)
    for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    y += 8
  }

  // TOPICS COVERED
  if (ai?.topics?.length) {
    heading('Topics covered')
    ai.topics.forEach((t, i) => {
      const ls = wrap(`${i + 1}. ${stripEmojis(t)}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // KEY POINTS
  if (ai?.keyPoints?.length) {
    heading('Key points')
    ai.keyPoints.forEach((k) => {
      const ls = wrap(`• ${stripEmojis(k)}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // FORMULAS
  if (ai?.formulas?.length) {
    heading('Formulas')
    ai.formulas.forEach((f) => {
      const ls = wrap(`• ${stripEmojis(f)}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // QUESTIONS
  if (ai?.questions?.length) {
    heading('Questions')
    ai.questions.forEach((q) => {
      const ls = wrap(`• ${stripEmojis(q)}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // MIND MAP — render as visual radial diagram (full frame, word-wrapped)
  if (l.mindmap_json) {
    nextPage()
    ensure(460)
    heading('Mind map')
    const center = stripEmojis(l.mindmap_json.center || title)
    const branches = (l.mindmap_json.branches || []).slice(0, 8)

    const wrapWords = (text: string, maxChars: number, maxLines: number): string[] => {
      if (!text) return ['']
      const words = text.split(/\s+/)
      const lines: string[] = []
      let cur = ''
      for (const w of words) {
        if (!cur) {
          cur = w
        } else if ((cur + ' ' + w).length <= maxChars) {
          cur += ' ' + w
        } else {
          lines.push(cur)
          cur = w
          if (lines.length >= maxLines) break
        }
      }
      if (cur && lines.length < maxLines) lines.push(cur)
      return lines.length > 0 ? lines : ['']
    }

    if (branches.length > 0) {
      const diagramH = 420
      ensure(diagramH + 20)

      const dW = W - 2 * M
      const dH = diagramH
      const dX = M
      const dY = y

      doc.setFillColor(250, 251, 253)
      doc.setDrawColor(230, 232, 238)
      doc.setLineWidth(0.5)
      doc.roundedRect(dX, dY, dW, dH, 10, 10, 'FD')

      const cx = dX + dW / 2
      const cy = dY + dH / 2
      const radius = Math.min(dW, dH) * 0.34
      const branchW = Math.min(170, dW / 3.2)

      const BRANCH_COLORS: [number, number, number][] = [
        [90, 143, 245],
        [52, 168, 83],
        [248, 180, 217],
        [255, 182, 39],
        [200, 168, 233],
        [255, 112, 67],
      ]

      const positions = branches.map((b, i) => {
        const total = branches.length
        const angle = -Math.PI + (i / total) * Math.PI * 2
        const bx = cx + Math.cos(angle) * radius
        const by = cy + Math.sin(angle) * radius * 0.82
        const titleLines = wrapWords(stripEmojis(b.title), 24, 2)
        const subLines = b.subtitle ? wrapWords(stripEmojis(b.subtitle), 28, 2) : []
        return { ...b, x: bx, y: by, titleLines, subLines, rgb: BRANCH_COLORS[i % BRANCH_COLORS.length] }
      })

      for (const pos of positions) {
        doc.setLineWidth(1)
        doc.setDrawColor(
          Math.round(pos.rgb[0] * 0.6 + 255 * 0.4),
          Math.round(pos.rgb[1] * 0.6 + 255 * 0.4),
          Math.round(pos.rgb[2] * 0.6 + 255 * 0.4),
        )
        doc.line(cx, cy, pos.x, pos.y)
      }

      const centerLines = wrapWords(center, 16, 2)
      const centerRadius = 48
      doc.setFillColor(29, 29, 31)
      doc.circle(cx, cy, centerRadius, 'F')

      doc.setTextColor(255, 255, 255)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(11)
      const lineHeight = 13
      const startCenterY = cy - ((centerLines.length - 1) * lineHeight) / 2 - 2
      centerLines.forEach((line, i) => {
        const w = doc.getTextWidth(line)
        doc.text(line, cx - w / 2, startCenterY + i * lineHeight)
      })

      doc.setFontSize(7)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor(255, 255, 255)
      const subtitle = 'Main Topic'
      const subW = doc.getTextWidth(subtitle)
      const subY = startCenterY + centerLines.length * lineHeight + 4
      doc.text(subtitle, cx - subW / 2, subY)

      for (const pos of positions) {
        const totalLines = pos.titleLines.length + pos.subLines.length
        const dynH = Math.max(40, 18 + totalLines * 12)

        doc.setFillColor(255, 255, 255)
        doc.setDrawColor(pos.rgb[0], pos.rgb[1], pos.rgb[2])
        doc.setLineWidth(1)
        doc.roundedRect(pos.x - branchW / 2, pos.y - dynH / 2, branchW, dynH, 8, 8, 'FD')

        doc.setTextColor(29, 29, 31)
        doc.setFont('helvetica', 'bold')
        doc.setFontSize(9)
        const titleLineH = 11
        const startTitleY = pos.y - ((totalLines - 1) * titleLineH) / 2 + 3
        pos.titleLines.forEach((line, lineIdx) => {
          const tw = doc.getTextWidth(line)
          doc.text(line, pos.x - tw / 2, startTitleY + lineIdx * titleLineH)
        })

        if (pos.subLines.length > 0) {
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(7.5)
          doc.setTextColor(107, 107, 112)
          const startSubY = startTitleY + pos.titleLines.length * titleLineH
          pos.subLines.forEach((line, lineIdx) => {
            const sw = doc.getTextWidth(line)
            doc.text(line, pos.x - sw / 2, startSubY + lineIdx * 10)
          })
        }
      }

      doc.setTextColor(...dark)
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      y = dY + dH + 12
    }
  }

  // CLEAN TRANSCRIPT — v61: segments with timestamps (matches dashboard layout)
  nextPage()
  heading('Clean transcript')

  if (l.clean_transcript_edited && l.clean_transcript_edited.trim()) {
    // Edited text — render as paragraphs
    const paragraphs = l.clean_transcript_edited.split(/\n+/)
    for (const p of paragraphs) {
      if (!p.trim()) { y += 6; continue }
      const clean = stripEmojis(p.replace(/^[-*]\s*/, '• '))
      const ls = wrap(clean, W - 2 * M, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
      y += 4
    }
  } else if (l.clean_segments && l.clean_segments.length > 0) {
    // Segments with timestamps — matches dashboard layout
    for (const seg of l.clean_segments) {
      ensure(40)

      // Timestamp label (gray, small)
      const tsLabel = `${fmtTime(seg.start)}  –  ${fmtTime(seg.end)}`
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(8.5)
      doc.setTextColor(...gray)
      doc.text(tsLabel, M, y)
      y += 4

      // Thin separator line
      doc.setDrawColor(...gray)
      doc.setLineWidth(0.3)
      doc.line(M, y, W - M, y)
      y += 10

      // Segment text
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(...dark)
      const ls = wrap(stripEmojis(seg.text), W - 2 * M, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
      y += 12
    }
  } else {
    // Fallback raw transcript
    const paragraphs = (l.transcript_md || '_No transcript_').split(/\n+/)
    for (const p of paragraphs) {
      if (!p.trim()) { y += 6; continue }
      const clean = stripEmojis(p.replace(/^[-*]\s*/, '• '))
      const ls = wrap(clean, W - 2 * M, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
      y += 4
    }
  }

  // IMAGES — embed each on a new section
  if (l.transcript_images && l.transcript_images.length > 0) {
    nextPage()
    heading('Images')

    for (const img of l.transcript_images) {
      const imgData = await imageUrlToBase64(img.url)
      if (!imgData) continue

      ensure(280)
      try {
        doc.addImage(imgData.data, imgData.format, M, y, 400, 240)
        y += 250

        if (img.caption) {
          doc.setFont('helvetica', 'italic')
          doc.setFontSize(10)
          doc.setTextColor(...gray)
          const ls = wrap(stripEmojis(img.caption), W - 2 * M, 10)
          for (const line of ls) { ensure(14); doc.text(line, M, y); y += 14 }
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(11)
          doc.setTextColor(...dark)
        }
        y += 12
      } catch (e) {
        console.warn('[pdf] failed to embed image:', e)
      }
    }
  }

  // FOOTER
  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFontSize(9)
    doc.setTextColor(...gray)
    doc.text(`Cotton Candy${opts.watermark ? ' · upgrade to remove this line' : ''}`, M, H - 20)
    doc.text(`${i} / ${pages}`, W - M, H - 20, { align: 'right' })
  }

  doc.save(`${stripEmojis(title).replace(/[^\w-]+/g, '_')}.pdf`)
}

// ---- keyword extraction ----
const STOP = new Set([
  'the','and','a','an','of','to','in','on','for','is','are','was','were','be','been','it','that','this','with','as','at','by','from','or','but','not','have','has','had','do','does','did','so','we','you','i','he','she','they','them','his','her','their','our','my','your','will','would','can','could','should','about','also','just','like','one','two','three','very','most','more','many','some','any','all','no','yes','there','here','then','than','when','where','what','how','who','why','which','because','if','such','each','into','through','over','under','between','after','before','during','without','again','only','own','same','too','these','those','up','down','out','off','now','today','well','okay','alright','really','actually','basically','essentially','maybe','probably','sort','kind','get','got','going','gonna','want','wanted','see','seen','make','makes','made','use','used','using','say','says','said','look','looks','looked','take','takes','took','taking','come','comes','came','give','gives','gave','ask','asked','asking','know','knows','knew','think','thinks','thought','thinking','find','found','fine','right','left',
])

export function extractKeywords(text: string, max = 10): string[] {
  const words = (text.toLowerCase().match(/[a-zA-Z][a-zA-Z\-]{2,}/g) || [])
  const freq = new Map<string, number>()
  for (const w of words) {
    if (STOP.has(w)) continue
    freq.set(w, (freq.get(w) || 0) + 1)
  }
  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, max)
    .map(([w]) => w)
}

export function secondsToClock(sec: number) {
  const h = Math.floor(sec / 3600)
  const m = Math.floor((sec % 3600) / 60)
  const s = sec % 60
  return [h, m, s].map((n) => String(n).padStart(2, '0')).join(':')
}
