import type { Lecture, ThemeTokens, MindMap, TranscriptImage } from '@/types'
import { THEMES } from '@/types'

// v60: AI summary type for export
type AISummaryExport = {
  summary?: string
  inferredTitle?: string
  topics?: string[]
  keyPoints?: string[]
  formulas?: string[]
  questions?: string[]
}

// --------- Markdown export (v60: with mind map as bullets + images as ![]() ) ---------
export function lectureToMarkdown(
  l: Lecture,
  ai?: AISummaryExport,
): string {
  const lines: string[] = []
  const date = new Date(l.started_at).toLocaleString()
  const title = ai?.inferredTitle || l.title || 'Untitled'

  lines.push(`# ${title}`, '')
  if (l.subject)  lines.push(`**Subject:** ${l.subject}  `)
  if (l.lecturer) lines.push(`**Lecturer:** ${l.lecturer}  `)
  if (l.location) lines.push(`**Location:** ${l.location}  `)
  lines.push(`**Date:** ${date}  `)
  lines.push(`**Duration:** ${Math.round((l.duration_seconds || 0) / 60)} min  `)
  lines.push('')

  if (l.keywords?.length) {
    lines.push('## Keywords', '')
    lines.push(l.keywords.map((k) => `\`${k}\``).join(' · '), '')
  }

  // AI sections
  if (ai?.summary) {
    lines.push('## ✨ Summary', '', ai.summary, '')
  }
  if (ai?.topics?.length) {
    lines.push('## 📌 Topics covered', '')
    ai.topics.forEach((t, i) => lines.push(`${i + 1}. ${t}`))
    lines.push('')
  }
  if (ai?.keyPoints?.length) {
    lines.push('## 🔑 Key points', '')
    ai.keyPoints.forEach((k) => lines.push(`- ${k}`))
    lines.push('')
  }
  if (ai?.formulas?.length) {
    lines.push('## 📐 Formulas', '')
    ai.formulas.forEach((f) => lines.push(`- ${f}`))
    lines.push('')
  }
  if (ai?.questions?.length) {
    lines.push('## ❓ Questions', '')
    ai.questions.forEach((q) => lines.push(`- ${q}`))
    lines.push('')
  }

  // v60: Mind map as nested bullets
  if (l.mindmap_json) {
    lines.push('## 🧠 Mind map', '')
    lines.push(`- **${l.mindmap_json.center}**`)
    for (const branch of l.mindmap_json.branches || []) {
      lines.push(`  - ${branch.title}`)
      if (branch.subtitle) lines.push(`    - _${branch.subtitle}_`)
    }
    lines.push('')
  }

  // v60: Clean transcript (edited if available, else from segments, else raw)
  lines.push('## 📝 Clean transcript', '')
  const cleanText = (l.clean_transcript_edited && l.clean_transcript_edited.trim())
    ? l.clean_transcript_edited
    : (l.clean_segments && l.clean_segments.length > 0)
      ? l.clean_segments.map(s => s.text).join('\n\n')
      : (l.transcript_md || '_No transcript_')
  lines.push(cleanText, '')

  // v60: Images
  if (l.transcript_images && l.transcript_images.length > 0) {
    lines.push('## 🖼️ Images', '')
    l.transcript_images.forEach((img, i) => {
      const caption = img.caption || `Image ${i + 1}`
      lines.push(`![${caption}](${img.url})`)
      if (img.caption) lines.push(`*${img.caption}*`)
      lines.push('')
    })
  }

  lines.push('---', '', '_Generated by Cotton Candy 🍭 · cottoncandy-s.com_')
  return lines.join('\n')
}

export function downloadText(filename: string, content: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// --------- PDF export (jsPDF) — v60: full content with mind map, images ---------
function hexToRgb(hex: string): [number, number, number] {
  const h = hex.replace('#', '')
  const r = parseInt(h.slice(0, 2), 16)
  const g = parseInt(h.slice(2, 4), 16)
  const b = parseInt(h.slice(4, 6), 16)
  return [r, g, b]
}

// Fetch image as base64 for PDF embedding
async function imageUrlToBase64(url: string): Promise<{ data: string; format: 'JPEG' | 'PNG' } | null> {
  try {
    const res = await fetch(url)
    if (!res.ok) return null
    const blob = await res.blob()
    const isJpeg = blob.type.includes('jpeg') || blob.type.includes('jpg')
    return new Promise((resolve) => {
      const reader = new FileReader()
      reader.onloadend = () => {
        const str = reader.result as string
        resolve({ data: str, format: isJpeg ? 'JPEG' : 'PNG' })
      }
      reader.onerror = () => resolve(null)
      reader.readAsDataURL(blob)
    })
  } catch {
    return null
  }
}

export async function lectureToPdf(
  l: Lecture,
  opts: { watermark?: boolean; theme?: ThemeTokens; ai?: AISummaryExport } = {}
) {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  const H = doc.internal.pageSize.getHeight()
  const M = 48
  let y = M

  const theme = opts.theme || THEMES.pink
  const pink = hexToRgb(theme.primary)
  const dark = hexToRgb(theme.dark)
  const gray = hexToRgb(theme.gray)
  const soft = hexToRgb(theme.soft)
  const accent = hexToRgb(theme.primaryDark)

  const nextPage = () => { doc.addPage(); y = M }
  const ensure = (h: number) => { if (y + h > H - M) nextPage() }
  const wrap = (txt: string, maxWidth: number, fontSize: number) => {
    doc.setFontSize(fontSize)
    return doc.splitTextToSize(txt, maxWidth) as string[]
  }

  const ai = opts.ai
  const title = ai?.inferredTitle || l.title || 'Lecture'

  // HEADER BAND
  doc.setFillColor(...pink)
  doc.rect(0, 0, W, 90, 'F')
  doc.setTextColor(...dark)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.text(title, M, 52)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(11)
  const meta: string[] = []
  if (l.subject)  meta.push(l.subject)
  if (l.lecturer) meta.push(l.lecturer)
  if (l.location) meta.push(l.location)
  meta.push(new Date(l.started_at).toLocaleDateString())
  doc.text(meta.join('  ·  '), M, 74)
  y = 120

  // Section helper
  const heading = (text: string, color: [number, number, number] = accent) => {
    ensure(34)
    doc.setTextColor(...color)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.text(text, M, y); y += 22
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    doc.setTextColor(...dark)
  }

  // SUMMARY
  if (ai?.summary) {
    heading('✨ Summary')
    const ls = wrap(ai.summary, W - 2 * M, 11)
    for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    y += 8
  }

  // TOPICS COVERED
  if (ai?.topics?.length) {
    heading('📌 Topics covered')
    ai.topics.forEach((t, i) => {
      const ls = wrap(`${i + 1}. ${t}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // KEY POINTS
  if (ai?.keyPoints?.length) {
    heading('🔑 Key points')
    ai.keyPoints.forEach((k) => {
      const ls = wrap(`• ${k}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // FORMULAS
  if (ai?.formulas?.length) {
    heading('📐 Formulas')
    ai.formulas.forEach((f) => {
      const ls = wrap(`• ${f}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // QUESTIONS
  if (ai?.questions?.length) {
    heading('❓ Questions')
    ai.questions.forEach((q) => {
      const ls = wrap(`• ${q}`, W - 2 * M - 10, 11)
      for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    })
    y += 8
  }

  // MIND MAP — render as nested indent
  if (l.mindmap_json) {
    heading('🧠 Mind map')
    const center = l.mindmap_json.center || title
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    const cls = wrap(`◆ ${center}`, W - 2 * M, 12)
    for (const line of cls) { ensure(16); doc.text(line, M, y); y += 16 }
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(11)
    for (const branch of l.mindmap_json.branches || []) {
      ensure(16)
      const bls = wrap(`  ▸ ${branch.title}`, W - 2 * M - 16, 11)
      for (const line of bls) { ensure(15); doc.text(line, M + 12, y); y += 15 }
      if (branch.subtitle) {
        doc.setTextColor(...gray)
        doc.setFont('helvetica', 'italic')
        const sls = wrap(`     ${branch.subtitle}`, W - 2 * M - 32, 10)
        for (const line of sls) { ensure(14); doc.text(line, M + 24, y); y += 14 }
        doc.setTextColor(...dark)
        doc.setFont('helvetica', 'normal')
      }
    }
    y += 10
  }

  // CLEAN TRANSCRIPT
  heading('📝 Clean transcript')
  const cleanText = (l.clean_transcript_edited && l.clean_transcript_edited.trim())
    ? l.clean_transcript_edited
    : (l.clean_segments && l.clean_segments.length > 0)
      ? l.clean_segments.map(s => s.text).join('\n\n')
      : (l.transcript_md || '_No transcript_')

  const paragraphs = cleanText.split(/\n+/)
  for (const p of paragraphs) {
    if (!p.trim()) { y += 6; continue }
    const isHeading = p.startsWith('##')
    if (isHeading) {
      ensure(28)
      doc.setFont('helvetica', 'bold')
      doc.setFontSize(13)
      doc.setTextColor(...accent)
      const txt = p.replace(/^#+\s*/, '')
      const ls = wrap(txt, W - 2 * M, 13)
      for (const line of ls) { ensure(18); doc.text(line, M, y); y += 18 }
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(11)
      doc.setTextColor(...dark)
      continue
    }
    const clean = p.replace(/^[-*]\s*/, '• ')
    const ls = wrap(clean, W - 2 * M, 11)
    for (const line of ls) { ensure(15); doc.text(line, M, y); y += 15 }
    y += 4
  }

  // IMAGES — embed each on a new section
  if (l.transcript_images && l.transcript_images.length > 0) {
    nextPage()
    heading('🖼️ Images')

    for (const img of l.transcript_images) {
      const imgData = await imageUrlToBase64(img.url)
      if (!imgData) continue

      ensure(280)
      try {
        // Fit image into max 400×280 pt area
        doc.addImage(imgData.data, imgData.format, M, y, 400, 240)
        y += 250

        if (img.caption) {
          doc.setFont('helvetica', 'italic')
          doc.setFontSize(10)
          doc.setTextColor(...gray)
          const ls = wrap(img.caption, W - 2 * M, 10)
          for (const line of ls) { ensure(14); doc.text(line, M, y); y += 14 }
          doc.setFont('helvetica', 'normal')
          doc.setFontSize(11)
          doc.setTextColor(...dark)
        }
        y += 12
      } catch (e) {
        console.warn('[pdf] failed to embed image:', e)
      }
    }
  }

  // FOOTER
  const pages = doc.getNumberOfPages()
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i)
    doc.setFontSize(9)
    doc.setTextColor(...gray)
    doc.text(`Cotton Candy${opts.watermark ? ' · upgrade to remove this line' : ''}`, M, H - 20)
    doc.text(`${i} / ${pages}`, W - M, H - 20, { align: 'right' })
  }

  doc.save(`${title.replace(/[^\w-]+/g, '_')}.pdf`)
}

// ---- keyword extraction ----
const STOP = new Set([
  'the','and','a','an','of','to','in','on','for','is','are','was','were','be','been','it','that','this','with','as','at','by','from','or','but','not','have','has','had','do','does','did','so','we','you','i','he','she','they','them','his','her','their','our','my','your','will','would','can','could','should','about','also','just','like','one','two','three','very','most','more','many','some','any','all','no','yes','there','here','then','than','when','where','what','how','who','why','which','because','if','such','each','into','through','over','under','between','after','before','during','without','again','only','own','same','too','these','those','up','down','out','off','now','today','well','okay','alright','really','actually','basically','essentially','maybe','probably','sort','kind','get','got','going','gonna','want','wanted','see','seen','make','makes','made','use','used','using','say','says','said','look','looks','looked','take','takes','took','taking','come','comes','came','give','gives','gave','ask','asked','asking','know','knows','knew','think','thinks','thought','thinking','find','found','fine','right','left',
])

export function extractKeywords(text: string, max = 10): string[] {
  const words = (text.toLowerCase().match(/[a-zA-Z][a-zA-Z\-]{2,}/g) || [])
  const freq = new Map<string, number>()
  for (const w of words) {
    if (STOP.has(w)) continue
    freq.set(w, (freq.get(w) || 0) + 1)
  }
  return [...freq.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, max)
    .map(([w]) => w)
}

export function secondsToClock(sec: number) {
  const h = Math.floor(sec / 3600)
  const m = Math.floor((sec % 3600) / 60)
  const s = sec % 60
  return [h, m, s].map((n) => String(n).padStart(2, '0')).join(':')
}
